# Header
menu:
  主页: /
  所有文章: /archives
  文集: /collection
  相册: /photo
  留言板: /about

# SubNav
subnav:
  github: "https://github.com/airingursb"
  jianshu: "http://www.jianshu.com/users/b7757a81a98f/latest_articles"
  weibo: "http://weibo.com/2696578192/profile?topnav=1&wvr=6"
  #rss: "#"
  #zhihu: "#"
  #douban: "#"
  #mail: "mailto:gx-deng@163.com"
  #facebook: "https://www.facebook.com/airing.gx"
  #google: "#"
  #twitter: "#"
  #linkedin: "#"
  wymusic: "http://music.163.com/#/user/home?id=94609819"

rss: /atom.xml

# Content
excerpt_link: more
fancybox: true
mathjax: true

# 是否开启动画效果
animate: true

# 是否在新窗口打开链接
open_in_new: false

# Miscellaneous
google_analytics: ''
favicon: /favicon.ico

#你的头像url
avatar: /img/face.png
#是否开启分享
share: true
#是否开启多说评论，填写你在多说申请的项目名称 
duoshuo: airingursb
#若使用disqus，请在博客config文件中填写disqus_shortname，并关闭多说评论
#duoshuo: true
#是否开启云标签
tagcloud: true

#是否开启友情链接
#不开启——
#friends: false
#开启——
friends:
  #安林镜界: http://ursb.me/
  NoMan: http://nomanteam.github.io/Hole/
  urdb.me: http://urdb.me/
  荏苒。: http://www.eyrefree.org/
#是否开启“关于我”。
#不开启——
#aboutme: false
#开启——
aboutme: 谢谢支持！使用支付宝扫码即可。